/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Trainer as PrismaTrainer,
  ClassModel as PrismaClassModel,
} from "@prisma/client";

export class TrainerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TrainerCountArgs, "select">): Promise<number> {
    return this.prisma.trainer.count(args);
  }

  async trainers<T extends Prisma.TrainerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrainerFindManyArgs>
  ): Promise<PrismaTrainer[]> {
    return this.prisma.trainer.findMany<Prisma.TrainerFindManyArgs>(args);
  }
  async trainer<T extends Prisma.TrainerFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrainerFindUniqueArgs>
  ): Promise<PrismaTrainer | null> {
    return this.prisma.trainer.findUnique(args);
  }
  async createTrainer<T extends Prisma.TrainerCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrainerCreateArgs>
  ): Promise<PrismaTrainer> {
    return this.prisma.trainer.create<T>(args);
  }
  async updateTrainer<T extends Prisma.TrainerUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrainerUpdateArgs>
  ): Promise<PrismaTrainer> {
    return this.prisma.trainer.update<T>(args);
  }
  async deleteTrainer<T extends Prisma.TrainerDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TrainerDeleteArgs>
  ): Promise<PrismaTrainer> {
    return this.prisma.trainer.delete(args);
  }

  async findClasses(
    parentId: string,
    args: Prisma.ClassModelFindManyArgs
  ): Promise<PrismaClassModel[]> {
    return this.prisma.trainer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .classes(args);
  }
}
